
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: depot-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - depot-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: depot-backend
    ports:
      - '4000:4000'
      - '1234:1234'
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/depot
      REDIS_URL:    redis://redis:6379
      NODE_ENV:     production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - depot-network
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: depot-postgres
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       depot
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - depot-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: depot-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - depot-network
    restart: unless-stopped

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston
    ports:
      - "2000:2000"
    privileged: true
    tmpfs:
      - /piston/jobs
    networks:
      - depot-network
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:

networks:
  depot-network:
    driver: bridge